sonar.ws.timeout=1200
sonar.sourceEncoding=UTF-8
sonar.python.coveragePlugin=cobertura
sonar.projectBaseDir=.
sonar.sources=.
sonar.exclusions=**/reports/**,**/config/**
sonar.coverage.exclusions=**/test/**
