sonar.ws.timeout=1200
sonar.sourceEncoding=UTF-8
sonar.python.coveragePlugin=cobertura
sonar.projectBaseDir=.
sonar.sources=.
sonar.exclusions=**/reports/**,**/config/**
sonar.coverage.exclusions=**/test/**
sonar.python.reportPath=reports/pytest.xml
sonar.python.coverage.reportPath=reports/coverage.xml
sonar.python.pylint.report=reports/pylint.xml
